
#ifndef MOTOR_DEFINES
#define MOTOR_DEFINES

// Motor 1 defines
#define MOTOR0_SIGNAL0_H PD7
#define MOTOR0_SIGNAL0_L PD6
#define MOTOR0_SIGNAL1_H PD5
#define MOTOR0_SIGNAL1_L PD4
#define MOTOR0_SIGNAL2_H PD3
#define MOTOR0_SIGNAL2_L PD2

#define MOTOR0_ALL_SIGNALS (1 << MOTOR0_SIGNAL0_H) | (1 << MOTOR0_SIGNAL0_L) | (1 << MOTOR0_SIGNAL1_H) | (1 << MOTOR0_SIGNAL1_L) | (1 << MOTOR0_SIGNAL2_H) | (1 << MOTOR0_SIGNAL2_L)

#define MOTOR0_WINDING0_HIGH        (1 << MOTOR0_SIGNAL0_H) | (1 << MOTOR0_SIGNAL0_L)
#define MOTOR0_WINDING0_LOW         0
#define MOTOR0_WINDING0_FLOATING    (1 << MOTOR0_SIGNAL0_L)

#define MOTOR0_WINDING1_HIGH        (1 << MOTOR0_SIGNAL1_H) | (1 << MOTOR0_SIGNAL1_L)
#define MOTOR0_WINDING1_LOW         0
#define MOTOR0_WINDING1_FLOATING    (1 << MOTOR0_SIGNAL1_L)

#define MOTOR0_WINDING2_HIGH        (1 << MOTOR0_SIGNAL2_H) | (1 << MOTOR0_SIGNAL2_L)
#define MOTOR0_WINDING2_LOW         0
#define MOTOR0_WINDING2_FLOATING    (1 << MOTOR0_SIGNAL2_L)

#define MOTOR0_ROTATION0 MOTOR0_WINDING0_HIGH       | MOTOR0_WINDING1_LOW       | MOTOR0_WINDING2_FLOATING
#define MOTOR0_ROTATION1 MOTOR0_WINDING0_HIGH       | MOTOR0_WINDING1_FLOATING  | MOTOR0_WINDING2_LOW
#define MOTOR0_ROTATION2 MOTOR0_WINDING0_FLOATING   | MOTOR0_WINDING1_HIGH      | MOTOR0_WINDING2_LOW 
#define MOTOR0_ROTATION3 MOTOR0_WINDING0_LOW        | MOTOR0_WINDING1_HIGH      | MOTOR0_WINDING2_FLOATING
#define MOTOR0_ROTATION4 MOTOR0_WINDING0_LOW        | MOTOR0_WINDING1_FLOATING  | MOTOR0_WINDING2_HIGH
#define MOTOR0_ROTATION5 MOTOR0_WINDING0_FLOATING   | MOTOR0_WINDING1_LOW       | MOTOR0_WINDING2_HIGH

#define MOTOR0_FLOATING0 MOTOR0_WINDING0_HIGH       | MOTOR0_WINDING1_LOW       | MOTOR0_WINDING2_FLOATING
#define MOTOR0_FLOATING1 MOTOR0_WINDING0_HIGH       | MOTOR0_WINDING1_FLOATING  | MOTOR0_WINDING2_LOW
#define MOTOR0_FLOATING2 MOTOR0_WINDING0_FLOATING   | MOTOR0_WINDING1_HIGH      | MOTOR0_WINDING2_LOW 
#define MOTOR0_FLOATING3 MOTOR0_WINDING0_LOW        | MOTOR0_WINDING1_HIGH      | MOTOR0_WINDING2_FLOATING
#define MOTOR0_FLOATING4 MOTOR0_WINDING0_LOW        | MOTOR0_WINDING1_FLOATING  | MOTOR0_WINDING2_HIGH
#define MOTOR0_FLOATING5 MOTOR0_WINDING0_FLOATING   | MOTOR0_WINDING1_LOW       | MOTOR0_WINDING2_HIGH

#define MOTOR0_PORT PORTD
#define MOTOR0_DDR DDRD


// motor 2 defines
#define MOTOR1_SIGNAL0_H PB5
#define MOTOR1_SIGNAL0_L PB4
#define MOTOR1_SIGNAL1_H PB3
#define MOTOR1_SIGNAL1_L PB2
#define MOTOR1_SIGNAL2_H PB1
#define MOTOR1_SIGNAL2_L PB0

#define MOTOR1_ALL_SIGNALS (1 << MOTOR1_SIGNAL0_H) | (1 << MOTOR1_SIGNAL0_L) | (1 << MOTOR1_SIGNAL1_H) | (1 << MOTOR1_SIGNAL1_L) | (1 << MOTOR1_SIGNAL2_H) | (1 << MOTOR1_SIGNAL2_L)

#define MOTOR1_WINDING0_HIGH        (1 << MOTOR1_SIGNAL0_H) | (1 << MOTOR1_SIGNAL0_L)
#define MOTOR1_WINDING0_LOW         0
#define MOTOR1_WINDING0_FLOATING    (1 << MOTOR1_SIGNAL0_L)

#define MOTOR1_WINDING1_HIGH        (1 << MOTOR1_SIGNAL1_H) | (1 << MOTOR1_SIGNAL1_L)
#define MOTOR1_WINDING1_LOW         0
#define MOTOR1_WINDING1_FLOATING    (1 << MOTOR1_SIGNAL1_L)

#define MOTOR1_WINDING2_HIGH        (1 << MOTOR1_SIGNAL2_H) | (1 << MOTOR1_SIGNAL2_L)
#define MOTOR1_WINDING2_LOW         0
#define MOTOR1_WINDING2_FLOATING    (1 << MOTOR1_SIGNAL2_L)

#define MOTOR1_ROTATION0 MOTOR1_WINDING0_HIGH       | MOTOR1_WINDING1_LOW       | MOTOR1_WINDING2_FLOATING
#define MOTOR1_ROTATION1 MOTOR1_WINDING0_HIGH       | MOTOR1_WINDING1_FLOATING  | MOTOR1_WINDING2_LOW
#define MOTOR1_ROTATION2 MOTOR1_WINDING0_FLOATING   | MOTOR1_WINDING1_HIGH      | MOTOR1_WINDING2_LOW 
#define MOTOR1_ROTATION3 MOTOR1_WINDING0_LOW        | MOTOR1_WINDING1_HIGH      | MOTOR1_WINDING2_FLOATING
#define MOTOR1_ROTATION4 MOTOR1_WINDING0_LOW        | MOTOR1_WINDING1_FLOATING  | MOTOR1_WINDING2_HIGH
#define MOTOR1_ROTATION5 MOTOR1_WINDING0_FLOATING   | MOTOR1_WINDING1_LOW       | MOTOR1_WINDING2_HIGH

#define MOTOR1_FLOATING0 MOTOR1_WINDING0_LOW        | MOTOR1_WINDING1_LOW       | MOTOR1_WINDING2_FLOATING
#define MOTOR1_FLOATING1 MOTOR1_WINDING0_LOW        | MOTOR1_WINDING1_FLOATING  | MOTOR1_WINDING2_LOW
#define MOTOR1_FLOATING2 MOTOR1_WINDING0_FLOATING   | MOTOR1_WINDING1_LOW       | MOTOR1_WINDING2_LOW 
#define MOTOR1_FLOATING3 MOTOR1_WINDING0_LOW        | MOTOR1_WINDING1_LOW       | MOTOR1_WINDING2_FLOATING
#define MOTOR1_FLOATING4 MOTOR1_WINDING0_LOW        | MOTOR1_WINDING1_FLOATING  | MOTOR1_WINDING2_LOW
#define MOTOR1_FLOATING5 MOTOR1_WINDING0_FLOATING   | MOTOR1_WINDING1_LOW       | MOTOR1_WINDING2_LOW

#define MOTOR1_PORT PORTB
#define MOTOR1_DDR DDRB

// Hallefect sensor defines motor 0
#define HALL_SENS_0_MOTOR0 PC0
#define HALL_SENS_1_MOTOR0 PC1
#define HALL_SENS_2_MOTOR0 PC2

#define HALL_SENS_MOTOR0_MASK (1 << HALL_SENS_0_MOTOR0) | (1 << HALL_SENS_1_MOTOR0) | (1 << HALL_SENS_2_MOTOR0)

// Hallefect sensor defines motor 1
#define HALL_SENS_0_MOTOR0 PC3
#define HALL_SENS_1_MOTOR0 PC4
#define HALL_SENS_2_MOTOR0 PC5

#define HALL_SENS_MOTOR1_MASK (1 << HALL_SENS_0_MOTOR1) | (1 << HALL_SENS_1_MOTOR1) | (1 << HALL_SENS_2_MOTOR1)

// TCCR0B Timer 0 clock controll
#define TCCR0_NO_CLOCK_MASK         0
#define TCCR0_PRESCALER_0_MASK      (1 << CS00)
#define TCCR0_PRESCALER_8_MASK       (1 << CS01)
#define TCCR0_PRESCALER_64_MASK      (1 << CS01) | (1 << CS00)
#define TCCR0_PRESCALER_256_MASK    (1 << CS02)
#define TCCR0_PRESCALER_1024_MASK   (1 << CS02) | (1 << CS00)
#define TCCR0_EXTERN_FALLING_MASK   (1 << CS02) | (1 << CS01)
#define TCCR0_EXTERN_RISING_MASK    (1 << CS02) | (1 << CS01) | (1 << CS00)


// TCCR1B Timer 1 clock controll
#define TCCR1_NO_CLOCK_MASK         0
#define TCCR1_PRESCALER_0_MASK      (1 << CS10)
#define TCCR1_PRESCALER_8_MASK       (1 << CS11)
#define TCCR1_PRESCALER_64_MASK      (1 << CS11) | (1 << CS10)
#define TCCR1_PRESCALER_256_MASK    (1 << CS12)
#define TCCR1_PRESCALER_1024_MASK   (1 << CS12) | (1 << CS10)
#define TCCR1_EXTERN_FALLING_MASK   (1 << CS12) | (1 << CS11)
#define TCCR1_EXTERN_RISING_MASK    (1 << CS12) | (1 << CS11) | (1 << CS10)


// TCCR2B Timer 2 clock controll
#define TCCR2_NO_CLOCK_MASK         0
#define TCCR2_PRESCALER_0_MASK      (1 << CS20)
#define TCCR2_PRESCALER_8_MASK       (1 << CS21)
#define TCCR2_PRESCALER_64_MASK      (1 << CS21) | (1 << CS20)
#define TCCR2_PRESCALER_256_MASK    (1 << CS22)
#define TCCR2_PRESCALER_1024_MASK   (1 << CS22) | (1 << CS20)
#define TCCR2_EXTERN_FALLING_MASK   (1 << CS22) | (1 << CS21)
#define TCCR2_EXTERN_RISING_MASK    (1 << CS22) | (1 << CS21) | (1 << CS20)


#endif